name: ❓ Ask a Question
description: Use this template to ask usage or design questions about Triceratops
title: "[QUESTION] "
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out! We're happy to help clarify any usage or design questions.

  - type: textarea
    id: context
    attributes:
      label: 🤔 What are you trying to do?
      description: Briefly explain your use case or what you're trying to understand.
      placeholder: e.g., "How can I compute model radio emission from a TDE?"
    validations:
      required: true

  - type: textarea
    id: attempts
    attributes:
      label: 🧪 What have you tried?
      description: Share relevant code or documentation links you've reviewed.
      placeholder: e.g., "I ran the ChevalierShockEngine but got an error."
